services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-reverse-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - nginx-network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nginx-network
      
  # DNS-01(duckdns) 전용 certbot
  certbot-duckdns:
    image: infinityofspace/certbot_dns_duckdns:latest
    container_name: certbot-duckdns
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/duckdns.ini:/etc/letsencrypt/duckdns.ini:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    name: nginx-network

volumes:
  nginx-logs:

